# Builder
FROM node:20-alpine as builder
WORKDIR /app
COPY . .
RUN yarn install && yarn build

# NGINX server
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
